language: python
python: 3.7
install:
  - 'pip install pipenv'
  - 'pipenv sync -d'
script:
  - coverage run -m pytest
  - cd coinchanger
  - zip ../coinchanger.zip changer.py
  - cd ..
  - mkdir build
  - cp coinchanger.zip build
after_success: bash <(curl -s https://codecov.io/bash)
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: sjones-aws-s3-lambda
  region: eu-central-1
  local_dir: build
on:
  branch: master